sudo: required
services:
  - docker

before_script:
  - echo 'Canada/Pacific' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - docker pull golang:1.8

script:
  - docker build .

notifications:
  slack:
    secure: P0sPDQTbcr79cg4VLDjTLA7Lz+EsESGjrHWK6cLgiPb45UkNRMgT1fEejHxlNjWF1bl/X2vLcjboJJ9BJjUcyKOE/51vzEeB6vEQSswCs3koz1U5p1UydpYyycjgRQbH70nzn8S7c1bZKO/WSEiskXxrY80Uwi2P6jwm1mHgDm/EPLlGIvKHj4D/iz6ctlwMZx+xsbH67hZ2KXND09eMAyUZRx1HowDQXtWvv+4mubj9Q5muO/h3T0zdEQSTW7ddwsGFYs2kiH15H4hQAyY6eibU7DwotGQuH+07iQgW9ruBV0gxoHsQ6VGabNtAxV9LbAzXJzLztTk0WHvE+ulNYe0AzgDmnsmySEOGUkKa7lW7C3sUuqTLjkoZPxqhgBa/KapR1ig7j+ISNJLhWH4FnGf6yLY93R40Qy25+8iMBZmso7o1Ji/E8dH6AHdTYOapERk24SdTjd7ajypQm7kCd73WcaoET2mOH/1zH31/ldoAaUWMmmUm7LJ0gqIXThX75qoomCb+SBvux0AfuMHl5Jt46E6Qkq3sGDTuX0j1B/+TxiicUCPfkb4u8i9BZOCsyJhkgSHZ13tnqlRkG0RiJHSDB/2fgVh+0Ryi0+ztOnsp9FN2PkWfEt2vF20w8ywhtx1S78o1yr8tc4/7JSd29Uu8TS4Lfgn6+1cETDCab4o=
