sudo: required
services:
  - docker

before_script:
  - echo 'Canada/Pacific' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - docker pull golang:1.8

script:
  - docker build .

notifications:
  slack:
    secure: ux6+hyrkxDycUlrAQzfGuaFYo1Hkxi2dnbzLtq6cKuILzJaL0HIabjTRo/T3NsMPBsrld9ECuI28sUmOmvLL2iAO7PvqhecooHrTrFVg3DOt1N9uws5gaYCXkeCiTk+k9OBXc9OzjbprkjqrN10usRzzVNeKJUrOAyoUQEs7BwyYBkXjXbnPX4+nRG/28Xx99LvSVyjzgA+XpIRC3C3HcPnyNguD4JogVC5ISILNnJzutCD5d+dkUJ/xao5J0t3TL4jcWmsX+yShLsyEwV0Lj7ED7qXiORQDUnzfhZDkYKbUFHDSzoFKRZsD4MeOFFuZWH6YsfLHpAoARu4zy2qCWvMWKEv/88pse/98sCKGgDvwa7NmZKTYoVv6a77QmdtgrV6fq0X6FX0jR6L8ieokTiPTEkXUaolf7nleAHkNixYMyaYKBCfxLHVcVkt3nBWMa/8drfS/Yy1dEiyTVYGz3S/hZHziy2tvZ8rnr5Nz3N5ThK9gs0PDDRzPg0xZUIINRYeIVHojdQgKkjgiKOeePmeGLTi/C2RjhntC9z9CND1/p5PDCf+IDN47G2bEXCiUtZANcMHn8e5AV3g48G2r80DXaYsP3m52cVRuXxpWvNmTyS4lBRR+xmy4fBGRHQLlFW3GqJ8ADVFZ78vdTEF76cZIzJAorJocxfSZh6oZbrU=
